name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        *Please provide as much detail as possible so we can test and resolve the issue as soon as possible.*

  - type: input
    id: tf-version
    attributes:
      label: Terraform Version
      description: What version of terraform are you running?
      placeholder: ex. 1.0.11
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version tag of the module are you consuming?
      placeholder: ex. v1
    validations:
      required: true

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version of the kubernetes are you deploying?
      placeholder: ex. 1.22
    validations:
      required: true

  # - type: checkboxes
  #   id: upgrade
  #   attributes:
  #     label: Upgrading?
  #     description: Did you encounter the issue when upgrading from a previous version of the module, terraform or kubernetes?
  #     options:
  #       - label: Upgrade?
  #         required: true

  # - type: checkboxes
  #   id: encountered-before
  #   attributes:
  #     label: Seen the issue elsewhere?
  #     description: Have you encountered the issue before?
  #     options:
  #       - label: Elsewhere?
  #         required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Explain the Issue
      description: What happened and what did you expect to happen?
      placeholder: Tell us what you saw!
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Data
      description: Please provide any relevant log data.
      placeholder: Redact any secret data from the log before posting.
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Let us know if you have a workaround or know how this can be resolved
      placeholder: Know a solution?
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
