name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        *Please provide as much detail as possible so we can test and resolve the issue as soon as possible.*

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version tag of the module are you consuming?
      placeholder: ex. v1
    validations:
      required: true

  - type: input
    id: tf-version
    attributes:
      label: Terraform Version
      description: What version of terraform are you running?
      placeholder: ex. 1.0.11
    validations:
      required: true
  
  - type: textarea
    id: provider-versions
    attributes:
      label: Provider Versions
      description: What terraform providers were used?
      placeholder: hashicorp/azurerm v2.87.0
    validations:
      required: true

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version of the kubernetes are you deploying?
      placeholder: ex. 1.22
    validations:
      required: true

  - type: dropdown
    id: upgrade
    attributes:
      label: Upgrade?
      description: Did you encounter the issue when upgrading from a previous version of the module, terraform or kubernetes?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: encountered-before
    attributes:
      label: Seen the issue elsewhere?
      description: Have you encountered the issue before?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour?
      description: What actually happened?
      placeholder: Tell us what you saw!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps we can take to reproduce the error?
      placeholder: Tell us how to reproduce the error!
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log Data
      description: Please provide any relevant log data.
      placeholder: Redact any secret data from the log before posting.
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Let us know if you have a workaround or know how this can be resolved
      placeholder: Know a solution?
    validations:
      required: false
