name: General Question
description: Ask a question to the maintainers
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: The Question
      description: What would you like to know?
      placeholder: Ask a question
    validations:
      required: true
